apiVersion: v1
kind: Pod
metadata:
  name: no-priv
spec:
  containers:
    - name: no-priv
      image: quay.io/podman/stable
      args:
        - sleep
        - "1000000"
      resources:
        limits:
          github.com/fuse: 1