apiVersion: v1
kind: Pod
metadata:
  name: no-priv2
spec:
  containers:
    - name: no-priv2
      image: mgoltzsche/podman:latest
      args:
        - sleep
        - "1000000"
      securityContext:
        runAsUser: 1000
      resources:
        limits:
          github.com/fuse: 1