apiVersion: v1
kind: Pod
metadata:
  name: no-priv
spec:
  containers:
    - name: no-priv
      image: doppelrittberger/podman-maven:latest
      imagePullPolicy: Always
      resources:
        limits:
          github.com/fuse: 1
      volumeMounts:
        - mountPath: /dev/net/tun
          name: tun
  volumes:
    - name: tun
      hostPath:
        path: /dev/net/tun